from app.models import db, College


def seed_colleges():
    Abilene_Christian = College(name='Abilene Christian', logo='Abilene_Christian.gif')
    Alabama = College(name='Alabama', logo='Alabama.gif')
    Arizona = College(name='Arizona', logo='Arizona.gif')
    Arizona_State = College(name='Arizona State', logo='Arizona_State.gif')
    Arkansas = College(name='Arkansas', logo='Arkansas.gif')
    Auburn = College(name='Auburn', logo='Auburn.gif')
    Baylor = College(name='Baylor', logo='Baylor.gif')
    Belmont = College(name='Belmont', logo='Belmont.gif')
    Bradley = College(name='Bradley', logo='Bradley.gif')
    Bucknell = College(name='Bucknell', logo='Bucknell.gif')
    Buffalo = College(name='Buffalo', logo='Buffalo.gif')
    Butler = College(name='Butler', logo='Butler.gif')
    Cal_State_Fullerton = College(name='Cal State Fullerton', logo='Cal_State_Fullerton.gif')
    Charleston = College(name='Charleston', logo='Charleston.gif')
    Cincinnati = College(name='Cincinnati', logo='Cincinnati.gif')
    Clemson = College(name='Clemson', logo='Clemson.gif')
    Colgate = College(name='Colgate', logo='Colgate.gif')
    Creighton = College(name='Creighton', logo='Creighton.gif')
    Davidson = College(name='Davidson', logo='Davidson.gif')
    Duke = College(name='Duke', logo='Duke.gif')
    Fairleigh_Dickinson = College(name='Fairleigh Dickinson', logo='Fairleigh_Dickinson.gif')
    Florida_State = College(name='Florida State', logo='Florida_State.gif')
    Florida = College(name='Florida', logo='Florida.gif')
    Gardner_Webb = College(name='Gardner-Webb', logo='Gardner_Webb.gif')
    Georgia_State = College(name='Georgia State', logo='Georgia_State.gif')
    Gonzaga = College(name='Gonzaga', logo='Gonzaga.gif')
    Houston = College(name='Houston', logo='Houston.gif')
    Iona = College(name='Iona', logo='Iona.gif')
    Iowa = College(name='Iowa', logo='Iowa.gif')
    Iowa_State = College(name='Iowa State', logo='Iowa_State.gif')
    Kansas_State = College(name='Kansas State', logo='Kansas_State.gif')
    Kansas = College(name='Kansas', logo='Kansas.gif')
    Kentucky = College(name='Kentucky', logo='Kentucky.gif')
    Liberty = College(name='Liberty', logo='Liberty.gif')
    Lipscomb = College(name='Lipscomb', logo='Lipscomb.gif')
    Louisville = College(name='Louisville', logo='Louisville.gif')
    Loyola_Chicago = College(name='Loyola Chicago', logo='Loyola_Chicago.gif')
    LSU = College(name='LSU', logo='LSU.gif')
    Marquette = College(name='Marquette', logo='Marquette.gif')
    Marshall = College(name='Marshall', logo='Marshall.gif')
    Maryland = College(name='Maryland', logo='Maryland.gif')
    Miami = College(name='Miami', logo='Miami.gif')
    Michigan_State = College(name='Michigan State', logo='Michigan_State.gif')
    Michigan = College(name='Michigan', logo='Michigan.gif')
    Mississippi_State = College(name='Mississippi State', logo='Mississippi_State.gif')
    Missouri = College(name='Missouri', logo='Missouri.gif')
    Montana = College(name='Montana', logo='Montana.gif')
    Murray_State = College(name='Murray State', logo='Murray_State.gif')
    NCCU = College(name='NCCU', logo='NCCU.gif')
    Nevada = College(name='Nevada', logo='Nevada.gif')
    New_Mexico_State = College(name='New Mexico State', logo='New_Mexico_State.gif')
    North_Carolina_State = College(name='North Carolina State', logo='North_Carolina_State.gif')
    North_Carolina = College(name='North Carolina', logo='North_Carolina.gif')
    North_Dakota_State = College(name='North Dakota State', logo='North_Dakota_State.gif')
    Northeastern = College(name='Northeastern', logo='Northeastern.gif')
    Northern_Kentucky = College(name='Northern Kentucky', logo='Northern_Kentucky.gif')
    Ohio_State = College(name='Ohio State', logo='Ohio_State.gif')
    Oklahoma = College(name='Oklahoma', logo='Oklahoma.gif')
    Old_Dominion = College(name='Old Dominion', logo='Old_Dominion.gif')
    Ole_Miss = College(name='Ole Miss', logo='Ole_Miss.gif')
    Oregon = College(name='Oregon', logo='Oregon.gif')
    Penn = College(name='Penn', logo='Penn.gif')
    Prairie_View_AM = College(name='Prairie View A&M', logo='Prairie_View_AM.gif')
    Providence = College(name='Providence', logo='Providence.gif')
    Purdue = College(name='Purdue', logo='Purdue.gif')
    Radford = College(name='Radford', logo='Radford.gif')
    Rhode_Island = College(name='Rhode Island', logo='Rhode_Island.gif')
    Saint_Louis = College(name='Saint Louis', logo='Saint_Louis.gif')
    Saint_Marys = College(name='Saint Mary\'s', logo='Saint_Marys.gif')
    San_Diego_State = College(name='San Diego State', logo='San_Diego_State.gif')
    Seton_Hall = College(name='Seton Hall', logo='Seton_Hall.gif')
    South_Dakota_State = College(name='South Dakota State', logo='South_Dakota_State.gif')
    St_Bonaventure = College(name='St. Bonaventure', logo='St_Bonaventure.gif')
    St_Johns = College(name='St. Johns\'', logo='St_Johns.gif')
    Stephen_F_Austin = College(name='Stephen F. Austin', logo='Stephen_F_Austin.gif')
    Syracuse = College(name='Syracuse', logo='Syracuse.gif')
    TCU = College(name='TCU', logo='TCU.gif')
    Temple = College(name='Temple', logo='Temple.gif')
    Tennessee = College(name='Tennessee', logo='Tennessee.gif')
    Texas_AM = College(name='Texas A&M', logo='Texas_A&M.gif')
    Texas_Southern = College(name='Texas Southern', logo='Texas_Southern.gif')
    Texas_Tech = College(name='Texas Tech', logo='Texas_Tech.gif')
    Texas = College(name='Texas', logo='Texas.gif')
    UC_Irvine = College(name='UC Irvine', logo='UC_Irvine.gif')
    UCF = College(name='UCF', logo='UCF.gif')
    UCLA = College(name='UCLA', logo='UCLA.gif')
    UMBC = College(name='UMBC', logo='UMBC.gif')
    UNC_Greensboro = College(name='UNC Greensboro', logo='UNC_Greensboro.gif')
    Utah_State = College(name='Utah State', logo='Utah_State.gif')
    VCU = College(name='VCU', logo='VCU.gif')
    Vermont = College(name='Vermont', logo='Vermont.gif')
    Villanova = College(name='Villanova', logo='Villanova.gif')
    Virginia_Tech = College(name='Virginia Tech', logo='Virginia_Tech.gif')
    Virginia = College(name='Virginia', logo='Virginia.gif')
    Washington = College(name='Washington', logo='Washington.gif')
    West_Virginia = College(name='West Virginia', logo='West_Virginia.gif')
    Wichita_State = College(name='Wichita State', logo='Wichita_State.gif')
    Wisconsin = College(name='Wisconsin', logo='Wisconsin.gif')
    Wofford = College(name='Wofford', logo='Wofford.gif')
    Wright_State = College(name='Wright State', logo='Wright_State.gif')
    Xavier = College(name='Xavier', logo='Xavier.gif')
    Yale = College(name='Yale', logo='Yale.gif')

    db.session.add(Abilene_Christian)
    db.session.add(Alabama)
    db.session.add(Arizona)
    db.session.add(Arizona_State)
    db.session.add(Arkansas)
    db.session.add(Auburn)
    db.session.add(Baylor)
    db.session.add(Belmont)
    db.session.add(Bradley)
    db.session.add(Bucknell)
    db.session.add(Buffalo)
    db.session.add(Butler)
    db.session.add(Cal_State_Fullerton)
    db.session.add(Charleston)
    db.session.add(Cincinnati)
    db.session.add(Clemson)
    db.session.add(Colgate)
    db.session.add(Creighton)
    db.session.add(Davidson)
    db.session.add(Duke)
    db.session.add(Fairleigh_Dickinson)
    db.session.add(Florida_State)
    db.session.add(Florida)
    db.session.add(Gardner_Webb)
    db.session.add(Georgia_State)
    db.session.add(Gonzaga)
    db.session.add(Houston)
    db.session.add(Iona)
    db.session.add(Iowa)
    db.session.add(Iowa_State)
    db.session.add(Kansas_State)
    db.session.add(Kansas)
    db.session.add(Kentucky)
    db.session.add(Liberty)
    db.session.add(Lipscomb)
    db.session.add(Louisville)
    db.session.add(Loyola_Chicago)
    db.session.add(LSU)
    db.session.add(Marquette)
    db.session.add(Marshall)
    db.session.add(Maryland)
    db.session.add(Miami)
    db.session.add(Michigan_State)
    db.session.add(Michigan)
    db.session.add(Mississippi_State)
    db.session.add(Missouri)
    db.session.add(Montana)
    db.session.add(Murray_State)
    db.session.add(NCCU)
    db.session.add(Nevada)
    db.session.add(New_Mexico_State)
    db.session.add(North_Carolina_State)
    db.session.add(North_Carolina)
    db.session.add(North_Dakota_State)
    db.session.add(Northeastern)
    db.session.add(Northern_Kentucky)
    db.session.add(Ohio_State)
    db.session.add(Oklahoma)
    db.session.add(Old_Dominion)
    db.session.add(Ole_Miss)
    db.session.add(Oregon)
    db.session.add(Penn)
    db.session.add(Prairie_View_AM)
    db.session.add(Providence)
    db.session.add(Purdue)
    db.session.add(Radford)
    db.session.add(Rhode_Island)
    db.session.add(Saint_Louis)
    db.session.add(Saint_Marys)
    db.session.add(San_Diego_State)
    db.session.add(Seton_Hall)
    db.session.add(South_Dakota_State)
    db.session.add(St_Bonaventure)
    db.session.add(St_Johns)
    db.session.add(Stephen_F_Austin)
    db.session.add(Syracuse)
    db.session.add(TCU)
    db.session.add(Temple)
    db.session.add(Tennessee)
    db.session.add(Texas_AM)
    db.session.add(Texas_Southern)
    db.session.add(Texas_Tech)
    db.session.add(Texas)
    db.session.add(UC_Irvine)
    db.session.add(UCF)
    db.session.add(UCLA)
    db.session.add(UMBC)
    db.session.add(UNC_Greensboro)
    db.session.add(Utah_State)
    db.session.add(VCU)
    db.session.add(Vermont)
    db.session.add(Villanova)
    db.session.add(Virginia_Tech)
    db.session.add(Virginia)
    db.session.add(Washington)
    db.session.add(West_Virginia)
    db.session.add(Wichita_State)
    db.session.add(Wisconsin)
    db.session.add(Wofford)
    db.session.add(Wright_State)
    db.session.add(Xavier)
    db.session.add(Yale)

    db.session.commit()


def undo_colleges():
    db.session.execute('TRUNCATE colleges RESTART IDENTITY CASCADE;')
    db.session.commit()
