from app.models import db, College


def seed_colleges():
    Alabama = College(name='Alabama', logo='Alabama.gif')
    Arizona = College(name='Arizona', logo='Arizona.gif')
    Arkansas = College(name='Arkansas', logo='Arkansas.gif')
    Auburn = College(name='Auburn', logo='Auburn.gif')
    Bucknell = College(name='Bucknell', logo='Bucknell.gif')
    Buffalo = College(name='Buffalo', logo='Buffalo.gif')
    Butler = College(name='Butler', logo='Butler.gif')
    Cal_State_Fullerton = College(name='Cal State Fullerton', logo='Cal_State_Fullerton.gif')
    Charleston = College(name='Charleston', logo='Charleston.gif')
    Cincinnati = College(name='Cincinnati', logo='Cincinnati.gif')
    Clemson = College(name='Clemson', logo='Clemson.gif')
    Creighton = College(name='Creighton', logo='Creighton.gif')
    Davidson = College(name='Davidson', logo='Davidson.gif')
    Duke = College(name='Duke', logo='Duke.gif')
    Florida_State = College(name='Florida State', logo='Florida_State.gif')
    Florida = College(name='Florida', logo='Florida.gif')
    Georgia_State = College(name='Georgia State', logo='Georgia_State.gif')
    Gonzaga = College(name='Gonzaga', logo='Gonzaga.gif')
    Houston = College(name='Houston', logo='Houston.gif')
    Iona = College(name='Iona', logo='Iona.gif')
    Kansas_State = College(name='Kansas State', logo='Kansas_State.gif')
    Kansas = College(name='Kansas', logo='Kansas.gif')
    Kentucky = College(name='Kentucky', logo='Kentucky.gif')
    Lipscomb = College(name='Lipscomb', logo='Lipscomb.gif')
    Radford = College(name='Radford', logo='Radford.gif')
    Loyola_Chicago = College(name='Loyola Chicago', logo='Loyola_Chicago.gif')
    Marshall = College(name='Marshall', logo='Marshall.gif')
    Miami = College(name='Miami', logo='Miami.gif')
    Michigan_State = College(name='Michigan State', logo='Michigan_State.gif')
    Michigan = College(name='Michigan', logo='Michigan.gif')
    Missouri = College(name='Missouri', logo='Missouri.gif')
    Montana = College(name='Montana', logo='Montana.gif')
    Murray_State = College(name='Murray State', logo='Murray_State.gif')
    Nevada = College(name='Nevada', logo='Nevada.gif')
    New_Mexico_State = College(name='New Mexico State', logo='New_Mexico_State.gif')
    North_Carolina_State = College(name='North Carolina State', logo='North_Carolina_State.gif')
    North_Carolina = College(name='North Carolina', logo='North_Carolina.gif')
    Ohio_State = College(name='Ohio State', logo='Ohio_State.gif')
    Oklahoma = College(name='Oklahoma', logo='Oklahoma.gif')
    Penn = College(name='Penn', logo='Penn.gif')
    Providence = College(name='Providence', logo='Providence.gif')
    Purdue = College(name='Purdue', logo='Purdue.gif')
    Rhode_Island = College(name='Rhode Island', logo='Rhode_Island.gif')
    San_Diego_State = College(name='San Diego State', logo='San_Diego_State.gif')
    Seton_Hall = College(name='Seton Hall', logo='Seton_Hall.gif')
    South_Dakota_State = College(name='South Dakota State', logo='South_Dakota_State.gif')
    St_Bonaventure = College(name='St. Bonaventure', logo='St_Bonaventure.gif')
    Stephen_F_Austin = College(name='Stephen F. Austin', logo='Stephen_F_Austin.gif')
    Syracuse = College(name='Syracuse', logo='Syracuse.gif')
    TCU = College(name='TCU', logo='TCU.gif')
    Tennessee = College(name='Tennessee', logo='Tennessee.gif')
    Texas_AM = College(name='Texas A&M', logo='Texas_A&M.gif')
    Texas_Southern = College(name='Texas Southern', logo='Texas_Southern.gif')
    Texas_Tech = College(name='Texas Tech', logo='Texas_Tech.gif')
    Texas = College(name='Texas', logo='Texas.gif')
    UCLA = College(name='UCLA', logo='UCLA.gif')
    UMBC = College(name='UMBC', logo='UMBC.gif')
    UNC_Greensboro = College(name='UNC Greensboro', logo='UNC_Greensboro.gif')
    Villanova = College(name='Villanova', logo='Villanova.gif')
    Virginia_Tech = College(name='Virginia Tech', logo='Virginia_Tech.gif')
    Virginia = College(name='Virginia', logo='Virginia.gif')
    West_Virginia = College(name='West Virginia', logo='West_Virginia.gif')
    Wichita_State = College(name='Wichita State', logo='Wichita_State.gif')
    Wright_State = College(name='Wright State', logo='Wright_State.gif')
    Xavier = College(name='Xavier', logo='Xavier.gif')
   
    db.session.add(Alabama)
    db.session.add(Arizona)
    db.session.add(Arkansas)
    db.session.add(Auburn)
    db.session.add(Bucknell)
    db.session.add(Buffalo)
    db.session.add(Butler)
    db.session.add(Cal_State_Fullerton)
    db.session.add(Charleston)
    db.session.add(Cincinnati)
    db.session.add(Clemson)
    db.session.add(Creighton)
    db.session.add(Davidson)
    db.session.add(Duke)
    db.session.add(Florida_State)
    db.session.add(Florida)
    db.session.add(Georgia_State)
    db.session.add(Gonzaga)
    db.session.add(Houston)
    db.session.add(Iona)
    db.session.add(Kansas_State)
    db.session.add(Kansas)
    db.session.add(Kentucky)
    db.session.add(Lipscomb)
    db.session.add(Loyola_Chicago)
    db.session.add(Marshall)
    db.session.add(Miami)
    db.session.add(Michigan_State)
    db.session.add(Michigan)
    db.session.add(Missouri)
    db.session.add(Montana)
    db.session.add(Murray_State)
    db.session.add(Nevada)
    db.session.add(New_Mexico_State)
    db.session.add(North_Carolina_State)
    db.session.add(North_Carolina)
    db.session.add(Ohio_State)
    db.session.add(Oklahoma)
    db.session.add(Penn)
    db.session.add(Providence)
    db.session.add(Purdue)
    db.session.add(Radford)
    db.session.add(Rhode_Island)
    db.session.add(San_Diego_State)
    db.session.add(Seton_Hall)
    db.session.add(South_Dakota_State)
    db.session.add(St_Bonaventure)
    db.session.add(Stephen_F_Austin)
    db.session.add(Syracuse)
    db.session.add(TCU)
    db.session.add(Tennessee)
    db.session.add(Texas_AM)
    db.session.add(Texas_Southern)
    db.session.add(Texas_Tech)
    db.session.add(Texas)
    db.session.add(UCLA)
    db.session.add(UMBC)
    db.session.add(UNC_Greensboro)
    db.session.add(Villanova)
    db.session.add(Virginia_Tech)
    db.session.add(Virginia)
    db.session.add(West_Virginia)
    db.session.add(Wichita_State)
    db.session.add(Wright_State)
    db.session.add(Xavier)

    db.session.commit()


def undo_colleges():
    db.session.execute('TRUNCATE colleges RESTART IDENTITY CASCADE;')
    db.session.commit()
