"""empty message

Revision ID: 7735dc780a6f
Revises: ad2cb293a690
Create Date: 2020-12-16 23:22:04.755362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7735dc780a6f'
down_revision = 'ad2cb293a690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('last_round_completed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'last_round_completed')
    # ### end Alembic commands ###
