"""empty message

Revision ID: 2aab3d4df9ad
Revises: 
Create Date: 2020-12-03 11:12:09.509851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aab3d4df9ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('logo', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('march_madness_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('seed_number', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('eliminated', sa.Boolean(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('game_num', sa.Integer(), nullable=False),
    sa.Column('winning_team_id', sa.Integer(), nullable=True),
    sa.Column('child_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['winning_team_id'], ['march_madness_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('draft_order', sa.String(length=512), nullable=True),
    sa.Column('draft_index', sa.Integer(), nullable=False),
    sa.Column('draft_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drafting', sa.Boolean(), nullable=False),
    sa.Column('current_drafter_id', sa.Integer(), nullable=True),
    sa.Column('time_limit_mins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_drafter_id'], ['league_users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_draft_per_league_year', 'drafts', ['league_id', 'year'], unique=True)
    op.create_table('game_team_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['march_madness_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafted_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('march_madness_team_id', sa.Integer(), nullable=False),
    sa.Column('league_user_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('selection_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['league_user_id'], ['league_users.id'], ),
    sa.ForeignKeyConstraint(['march_madness_team_id'], ['march_madness_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_per_draft', 'drafted_teams', ['draft_id', 'march_madness_team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_per_draft', table_name='drafted_teams')
    op.drop_table('drafted_teams')
    op.drop_table('game_team_scores')
    op.drop_index('unique_draft_per_league_year', table_name='drafts')
    op.drop_table('drafts')
    op.drop_table('league_users')
    op.drop_table('games')
    op.drop_table('march_madness_teams')
    op.drop_table('leagues')
    op.drop_table('users')
    op.drop_table('colleges')
    # ### end Alembic commands ###
