"""empty message

Revision ID: 22c2340a1327
Revises: 7735dc780a6f
Create Date: 2020-12-18 16:00:33.227217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c2340a1327'
down_revision = '7735dc780a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('tournament_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'games', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'tournament_id')
    # ### end Alembic commands ###
