"""empty message

Revision ID: d28a063b1766
Revises: c3909cf8cbbe
Create Date: 2020-12-28 15:34:45.672497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28a063b1766'
down_revision = 'c3909cf8cbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_user_per_league', 'league_users', ['user_id', 'league_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_per_league', table_name='league_users')
    # ### end Alembic commands ###
