"""empty message

Revision ID: 4ee680ab1614
Revises: 87f05bac6e4d
Create Date: 2020-12-16 22:01:31.077136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee680ab1614'
down_revision = '87f05bac6e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_team_scores', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_team_scores', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
