"""empty message

Revision ID: ad2cb293a690
Revises: 4ee680ab1614
Create Date: 2020-12-16 22:20:10.840979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2cb293a690'
down_revision = '4ee680ab1614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('tournament_id', sa.Integer(), nullable=False))
    op.create_index('unique_draft_per_league_per_tournament', 'drafts', ['league_id', 'tournament_id'], unique=True)
    op.drop_index('unique_draft_per_league_year', table_name='drafts')
    op.create_foreign_key(None, 'drafts', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('drafts', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'drafts', type_='foreignkey')
    op.create_index('unique_draft_per_league_year', 'drafts', ['league_id', 'year'], unique=True)
    op.drop_index('unique_draft_per_league_per_tournament', table_name='drafts')
    op.drop_column('drafts', 'tournament_id')
    # ### end Alembic commands ###
