"""empty message

Revision ID: c3909cf8cbbe
Revises: 22c2340a1327
Create Date: 2020-12-25 14:24:19.394421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3909cf8cbbe'
down_revision = '22c2340a1327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'leagues', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='unique')
    # ### end Alembic commands ###
