"""empty message

Revision ID: 5072546c208c
Revises: d28a063b1766
Create Date: 2022-03-16 12:49:31.974956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5072546c208c'
down_revision = 'd28a063b1766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, default=False))
    op.execute("UPDATE users SET is_admin = false")
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
