"""empty message

Revision ID: 3a200877bab1
Revises: a83e91e68541
Create Date: 2022-03-18 13:00:08.763773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a200877bab1'
down_revision = 'a83e91e68541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_team_per_game', 'game_team_scores', ['game_id', 'team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_team_per_game', table_name='game_team_scores')
    # ### end Alembic commands ###
